import { defineConfig } from 'tsup';

export default defineConfig({
    entry: ['server.js'],
    format: ['cjs'],
    clean: true,
    minify: true,
    platform: 'node',
    target: 'node20',
    outDir: 'dist-server',
    noExternal: [
        'express',
        'http-proxy-middleware',
        'body-parser',
        'debug',
        'http-errors',
        'on-finished',
        'qs',
        'statuses',
        'type-is',
        'accepts',
        'content-disposition',
        'content-type',
        'cookie',
        'cookie-signature',
        'depd',
        'encodeurl',
        'escape-html',
        'etag',
        'finalhandler',
        'fresh',
        'merge-descriptors',
        'methods',
        'parseurl',
        'path-to-regexp',
        'proxy-addr',
        'range-parser',
        'safe-buffer',
        'send',
        'serve-static',
        'setprototypeof',
        'utils-merge',
        'vary'
    ],
    splitting: false,
    sourcemap: false
});
